---

- name: Ensure dependencies are installed
  apt:
    name: "{{ installation_dependecies }}"
    state: present
    update_cache: yes
  register: install_dependecies
  retries: 6
  delay: 10
  until: install_dependecies is success
  
- name: Download and unarchive additional software
  unarchive:
    src: "{{ item }}"
    dest: /usr/local/bin
    remote_src: yes
    mode: 755
  with_items:
    - "{{ terraform_pkg_url }}"
    - "{{ packer_pkg_url }}"
    