---
- name: Install Java
  apt: 
    name: default-jdk
    state: present
    update_cache: yes

- name: add group "tomcat"
  group: 
    name: tomcat

- name: add user "tomcat"
  user: 
    name: tomcat 
    group: tomcat 

- name: Create tomcat directory 
  file:
    path: "/opt/tomcat"
    owner: tomcat
    group: tomcat
    state: directory
    mode: 0755

- name: Download and unarchive tomcat
  unarchive:
    src: "{{ tomcat_pkg_url }}"
    dest: /opt/tomcat
    remote_src: yes
    owner: tomcat
    group: tomcat
    extra_opts: [--strip-components=1]

- name: Updated tomcat directory permissions 
  file:
    path: "/opt/tomcat"
    owner: tomcat
    group: tomcat
    recurse: yes

- name: Updated tomcat conf permissions 
  file:
    path: "/opt/tomcat/conf"
    owner: tomcat
    group: tomcat
    recurse: yes
    mode: 775

- name: Updated tomcat dir permissions 
  file:
    path: "/opt/tomcat/conf"
    owner: tomcat
    group: tomcat
    recurse: yes
    mode: "g+w"

- name: Add tomcat service
  template: 
    src: tomcat.service.j2
    dest: /etc/systemd/system/tomcat.service

- name: force systemd to reread configs 
  systemd:
    daemon_reload: yes

- name: tomcat-8-start
  service: 
    name: tomcat 
    state: started 
    enabled: yes